version: '3.3'

networks:
  laravel:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  app:
    build:
      context: ./dockerfiles
      dockerfile: app/dockerfile
    container_name: app
    volumes:
      - ./src/:/var/www/
    networks:
      - laravel

  node:
    build:
      context: .
      dockerfile: dockerfiles/node/dockerfile
    container_name: node
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./src/:/var/www/
      - /var/www/node_modules
    networks:
      - laravel

  mysql:
    build:
      context: .
      dockerfile: dockerfiles/mysql/dockerfile
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'laravel'
      MYSQL_PASSWORD: 'root'
    networks:
      - laravel
    volumes:
      - ./dockerfiles/mysql/dump:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel
#    volumes:
#      - ./dockerfiles/redis:/data